/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appearance: typeof import('./src/components/settings/Appearance.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    CashRegisterCard: typeof import('./src/components/CashRegisterCard.vue')['default']
    ColumnSettingsDialog: typeof import('./src/components/table/ColumnSettingsDialog.vue')['default']
    Company: typeof import('./src/components/settings/Company.vue')['default']
    DateRangeSelector: typeof import('./src/components/DateRangeSelector.vue')['default']
    FilterTableDialog: typeof import('./src/components/table/FilterTableDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IlterTableDialog: typeof import('./src/components/table/ilterTableDialog.vue')['default']
    Integrations: typeof import('./src/components/settings/Integrations.vue')['default']
    Logo: typeof import('./src/components/logo.vue')['default']
    Placeholder: typeof import('./src/components/settings/Placeholder.vue')['default']
    ReuseTable: typeof import('./src/components/table/reuseTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePanel: typeof import('./src/components/table/tablePanel.vue')['default']
  }
}
