/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/addressbook': RouteRecordInfo<'/addressbook', '/addressbook', Record<never, never>, Record<never, never>>,
    '/cashregister': RouteRecordInfo<'/cashregister', '/cashregister', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/export': RouteRecordInfo<'/export', '/export', Record<never, never>, Record<never, never>>,
    '/items': RouteRecordInfo<'/items', '/items', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/sales': RouteRecordInfo<'/sales', '/sales', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/support': RouteRecordInfo<'/support', '/support', Record<never, never>, Record<never, never>>,
    '/warehouse': RouteRecordInfo<'/warehouse', '/warehouse', Record<never, never>, Record<never, never>>,
  }
}
